### ISSUE TITLE
[Arduino Barebones] PCB

### ISSUE THREAD

**Issue by hkblock** [wduraes/Workshops#7]
Notes I jotted from the part three workshop:
- Add + to buzzer silkscreen
- Cover power-VCC trace (but I learned a lot!)
- Add notes on SMD soldering for voltage regulator
- Increasing solder pad size on the PCB for easier soldering: can't easily do in EasyEDA; manual task? :(

**Comment by hkblock** [comment]
Where is R3? (I assume it's the pot.)

**Comment by Pencab** [comment]
https://github.com/wduraes/Workshops/issues/7#issuecomment-815468781

**Comment by wduraes** [comment]
- "+" symbol added to the PCB top silk layer.
- I did not cover that trace because the goal is to have that talking point with students. It is also a great way to show and tell about increasing trace thickness....
- Can you elaborate on what notes need to be added? 
- That would impact clearance and probably would require a redesign of the traces. I'll keep that in mind for future designs! One thing I did on that design was to minimize thermal relief in all GND pins, to make it easier to solder. 

R3 is the potentiometer. I renamed it later....

Thanks for the comments!
